
### create organizer
POST http://localhost:3000/author-api/author
Content-Type: application/json

{
  "role": "author",
  "firstName": "author1",
  "lastName": "author1",
  "email": "author1@mail.com",
  "profileImageUrl": "author image",
  "isActive": true
}

###create student
POST http://localhost:3000/user-api/user
Content-Type: application/json

{
  "role": "user",
  "firstName": "user1",
  "lastName": "user1",
  "email": "author1@mail.com",
  "profileImageUrl": "user image",
  "isActive": true
}


###post new event by organizor
POST http://localhost:3000/author-api/article
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": true
   
}

###register event by student
POST http://localhost:3000/user-api/register
Content-Type: application/json

{
  "event_name": "Sintillashunz",
  "roll_no": "23071A0547",
  "full_name": "Pranati Rao Pinisetti",
  "email": "pranatiraop@gmail.com",
  "branch": "Computer Science",
  "section": "A",
  "gender": "Female",
  "phone_number": "9032017652"  
}

### Read all events by student
GET http://localhost:3000/user-api/articles


### Read all articles by organizer
GET http://localhost:3000/author-api/articles


### edit event by title
PUT http://localhost:3000/author-api/article/1740127871
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": true
}

### delete event by event title
PUT http://localhost:3000/author-api/articles/1740126354
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": false
   
}
###admin
get http://localhost:3000/admin-api/dashboard
