
### create author
POST http://localhost:3000/author-api/author
Content-Type: application/json

{
  "role": "author",
  "firstName": "author1",
  "lastName": "author1",
  "email": "author1@mail.com",
  "profileImageUrl": "author image",
  "isActive": true
}

###create user
POST http://localhost:3000/user-api/user
Content-Type: application/json

{
  "role": "user",
  "firstName": "user1",
  "lastName": "user1",
  "email": "author1@mail.com",
  "profileImageUrl": "user image",
  "isActive": true
}


###post new article
POST http://localhost:3000/author-api/article
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": true
   
}

### Read all articles by user
GET http://localhost:3000/user-api/articles


### Read all articles by author
GET http://localhost:3000/author-api/articles


### edit article by id
PUT http://localhost:3000/author-api/article/1740127871
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": true
}

### post comment by article id
PUT http://localhost:3000/user-api/comment/1740127871
Content-Type: application/json

{
      "nameOfUser": "user1",
      "comment": "Best article!"
     
}

### delete atricle by article id
### To do soft delete we are just updating the isArticleActive status to false
PUT http://localhost:3000/author-api/articles/1740126354
Content-Type: application/json

{
    "title": "abcd",
    "description":"efgh",
    "category":"other",
    "location":"JSK",
    "start_time":"{{$datetime iso8601}}",
    "end_time":"{{$datetime iso8601}}",
    "ticket_type": "free",
    "ticket_price": 0,
    "participant_limit": 100,
    "participant_count": 0,
    "registered_emails": ["abc@gmail.com", "123@gmail.com"],
    "created_at": "{{$datetime iso8601}}",
    "isArticleActive": false
   
}
###admin
get http://localhost:3000/admin-api/dashboard
